services:

  web:
    build: .
    container_name: django_weather
    command: gunicorn --bind 0.0.0.0:8000 weather.wsgi:application
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    expose:
      - "8000"

      

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/staticfiles:/app/staticfiles
    depends_on:
      - web